version: '3'
services:
  db:
    image: mysql:5.7.20
    container_name: championshipdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=championship
      - MYSQL_ROOT_PASSWORD=admin
  app:
    container_name: championship
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
