spring:
  profiles: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:championship;MODE=MySQL
    platform: h2

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

