server:
  ##servlet:
   ## context-path: "/santex-api"
  port: 8080

spring:
  application:
    name: "championship"

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
      path-mapping:
        metrics: "metrics-name"
        prometheus: "metrics"