spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/championship
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    platform: prod
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

