use `championship`;

CREATE TABLE IF NOT EXISTS `COMPETITION`(
    `ID` INT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `AREA_NAME` VARCHAR(255) NOT NULL,
    `CODE` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`ID`)
);

CREATE TABLE IF NOT EXISTS `TEAM`(
    `ID` INT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `SHORT_NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `TLA` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `COMPETITION_TEAM`(
    `COMPETITION_ID` INT NOT NULL,
    `TEAM_ID` INT NOT NULL,
    PRIMARY KEY (`TEAM_ID`,`COMPETITION_ID`)
    FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM`(`ID`),
    FOREIGN KEY (`COMPETITION_ID`) REFERENCES `COMPETITION`(`ID`)
);


CREATE TABLE IF NOT EXISTS `PLAYER` (
  `ID` INT NOT NULL,
  `TEAM_ID` INT NOT NULL,
  `DATE_OF_BIRTH` datetime DEFAULT NULL,
  `COUNTRY_OF_BIRTH` VARCHAR(255) DEFAULT NULL,
  `ROLE` VARCHAR(255) DEFAULT NULL,
  `NATIONALITY` VARCHAR(255) DEFAULT NULL,
  `POSITION` VARCHAR(255) DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
  FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM`(`ID`)
);