use `championship`;

CREATE TABLE IF NOT EXISTS `COMPETITION`(
    `ID` BIGINT AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(255),
    `AREA_NAME` VARCHAR(255),
    `CODE` VARCHAR(255),
    PRIMARY KEY(`ID`)
);

CREATE TABLE IF NOT EXISTS `TEAM`(
    `ID` BIGINT AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(255),
    `SHORT_NAME` VARCHAR(255),
    `EMAIL` VARCHAR(255),
    `TLA` VARCHAR(255),
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `COMPETITION_TEAM`(
    `COMPETITION_ID` BIGINT,
    `TEAM_ID` BIGINT,
    PRIMARY KEY (`TEAM_ID`,`COMPETITION_ID`),
    CONSTRAINT FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM`(`ID`),
    CONSTRAINT FOREIGN KEY (`COMPETITION_ID`) REFERENCES `COMPETITION`(`ID`)
);


CREATE TABLE IF NOT EXISTS `PLAYER` (
  `ID` BIGINT AUTO_INCREMENT NOT NULL,
  `TEAM_ID` BIGINT,
  `DATE_OF_BIRTH` datetime DEFAULT NULL,
  `COUNTRY_OF_BIRTH` VARCHAR(255) DEFAULT NULL,
  `ROLE` VARCHAR(255) DEFAULT NULL,
  `NATIONALITY` VARCHAR(255) DEFAULT NULL,
  `POSITION` VARCHAR(255) DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM`(`ID`)
);